import { useState } from "react";
import { fmt, fmtMoney, buildChart, STREAMING_PLATFORMS, BASE_STREAMING_RATE, SPOTIFY_MIN_STREAMS } from "../gameLogic";

export default function MusicTab(game: any) {
  const { state, doPromoteTrack, doShootMusicVideo, doReleaseProject, doDeleteUnreleased } = game;
  const [view, setView] = useState<"releases" | "insights">("releases");
  const [selectedTrack, setSelectedTrack] = useState<string | null>(null);
  const totalWeeklyStreams = state.catalog.reduce((sum: number, track: any) => sum + (track.weeklyStreams || 0), 0);
  const totalWeeklyRevenue = state.catalog.reduce((sum: number, track: any) => sum + (track.streamStats?.weeklyRevenue || 0), 0);
  const avgRate = totalWeeklyStreams > 0 ? totalWeeklyRevenue / totalWeeklyStreams : 0;
  const chart = buildChart(state.catalog, state.week);
  const mySongs = chart.filter((entry: any) => entry.isMe);

  return <div className="animate-fadeIn music-workspace">
    <header className="music-header">
      <div><div className="pg-title">Music</div><div className="tip-text">Your releases and the stories they are building.</div></div>
      <div className="music-header-stat"><span>This week</span><strong>{fmt(totalWeeklyStreams)}</strong><small>{fmtMoney(totalWeeklyRevenue)}</small></div>
    </header>
    <div className="music-switcher" role="tablist" aria-label="Music views">
      <button role="tab" aria-selected={view === "releases"} className={view === "releases" ? "active" : ""} onClick={() => setView("releases")}>Releases</button>
      <button role="tab" aria-selected={view === "insights"} className={view === "insights" ? "active" : ""} onClick={() => setView("insights")}>Insights</button>
    </div>

    {view === "releases" && <div className="music-release-shelf stagger-1">
      {state.unreleased.length > 0 && <section className="music-shelf-section"><div className="music-section-heading"><div><div className="music-section-kicker">Ready when you are</div><h2>Unreleased</h2></div></div>{state.unreleased.map((project: any) => <article className="music-release-card music-release-card--unreleased" key={project.id}><div><div className="rel-title">{project.title}</div><div className="rel-meta">{project.type} · Quality {project.avgQuality.toFixed(0)}</div></div><div className="music-release-actions"><button className="btn btn-sm btn-lime" onClick={() => doReleaseProject(project.id)}>Release</button><button className="btn btn-sm btn-danger" onClick={() => doDeleteUnreleased(project.id)}>Delete</button></div></article>)}</section>}
      <section className="music-shelf-section"><div className="music-section-heading"><div><div className="music-section-kicker">Your story so far</div><h2>Discography</h2></div></div>{state.discography.length === 0 ? <div className="empty-state">No releases yet. Record something!</div> : state.discography.map((release: any) => <article className={`music-release-card ${release.outcome === "Viral" ? "viral" : release.outcome === "Hit" ? "hit" : release.outcome === "Flop" ? "flop" : ""}`} key={release.id}><div><div className="rel-title">{release.title}</div><div className="rel-meta">{release.type} · Week {release.releasedWeek}</div></div><div className="music-release-result"><span className={`tag ${release.outcome === "Viral" ? "t-gold" : release.outcome === "Hit" ? "t-lime" : release.outcome === "Moderate" ? "t-orange" : "t-red"}`}>{release.outcome}</span><small>{fmtMoney(release.revenue)} · +{fmt(release.fansGained)} fans</small></div></article>)}</section>
    </div>}

    {view === "insights" && <div className="music-insights stagger-1">
      <section className="music-insight-summary"><div><span>Weekly streams</span><strong>{fmt(totalWeeklyStreams)}</strong></div><div><span>Weekly revenue</span><strong className="text-sage">{fmtMoney(totalWeeklyRevenue)}</strong></div><div><span>Average rate</span><strong>{avgRate.toFixed(4)}¢</strong></div></section>
      <details className="music-insight-panel"><summary><span>Catalog performance</span><small>{state.catalog.length} active release{state.catalog.length === 1 ? "" : "s"}</small></summary><div className="music-insight-body">{state.catalog.length === 0 ? <div className="empty-state">No releases in catalog. Record something!</div> : state.catalog.map((track: any) => { const stats = track.streamStats || {}; const fillPct = track.peakStreams > 0 ? Math.min(100, (track.weeklyStreams / track.peakStreams) * 100) : 0; const isSelected = selectedTrack === track.id; const hitThreshold = track.totalStreams >= SPOTIFY_MIN_STREAMS; return <article className="music-catalog-item" key={track.id}><button className="music-catalog-main" aria-expanded={isSelected} onClick={() => setSelectedTrack(isSelected ? null : track.id)}><span><b>{track.title}</b><small>{track.type} · {track.lifecycle}</small></span><span>{fmt(track.weeklyStreams)} / wk</span></button>{isSelected && <div className="music-catalog-detail"><div className="stream-bar-track"><div className="stream-bar-fill" style={{ width: `${fillPct}%` }} /></div><div className="music-detail-metrics"><span>Peak {fmt(track.peakStreams)}</span><span>Total {fmt(track.totalStreams)}</span><span>{fmtMoney(stats.weeklyRevenue || 0)} this week</span><span>{fmtMoney(stats.lifetimeRevenue || 0)} lifetime</span></div>{!hitThreshold && <div className="text-rust">{fmt(SPOTIFY_MIN_STREAMS - track.totalStreams)} to streaming threshold</div>}<div className="music-release-actions"><button className="btn btn-sm" disabled={state.money < 350 || track.promoted} onClick={() => doPromoteTrack(track.id)}>Promote ($350)</button><button className="btn btn-sm" disabled={state.money < 1200 || track.hasMusicVideo} onClick={() => doShootMusicVideo(track.id)}>Video ($1.2k)</button></div><details className="music-nested-detail"><summary>Platform and audience breakdown</summary><div className="music-detail-metrics">{STREAMING_PLATFORMS.map((platform: any) => <span key={platform.id}>{platform.name}: {Math.round((track.platformMix?.[platform.id] || 0) * 100)}%</span>)}{Object.entries(track.geoDist || {}).map(([country, share]: [string, any]) => <span key={country}>{country}: {Math.round(share * 100)}%</span>)}</div></details></div>}</article>; })}</div></details>
      <details className="music-insight-panel"><summary><span>Charts</span><small>{mySongs.length ? `${mySongs.length} of your songs charting` : "No songs charting"}</small></summary><div className="music-insight-body">{mySongs.length > 0 && <div className="music-chart-group"><div className="studio-option-label">Your positions</div>{mySongs.map((entry: any) => <div key={entry.id} className="chart-row me"><div className={`chart-pos ${entry.pos <= 3 ? "top3" : ""}`}>#{entry.pos}</div><div style={{ flex: 1 }}>{entry.title}</div><div>{fmt(entry.streams)}</div></div>)}</div>}<details className="music-nested-detail"><summary>Top 20 chart</summary>{chart.slice(0, 20).map((entry: any) => <div className={`chart-row ${entry.isMe ? "me" : ""}`} key={`${entry.pos}-${entry.title}`}><div className={`chart-pos ${entry.pos <= 3 ? "top3" : ""}`}>#{entry.pos}</div><div style={{ flex: 1 }}>{entry.title}</div><div className="text-muted">{entry.artist}</div></div>)}</details></div></details>
      <details className="music-insight-panel"><summary><span>Streaming analytics</span><small>Revenue, platforms, and audience</small></summary><div className="music-insight-body"><div className="music-analytics-grid"><div><span>Lifetime revenue</span><strong className="text-sage">{fmtMoney(state.totalStreamingRevenue || 0)}</strong></div><div><span>Average payout</span><strong>{avgRate.toFixed(4)}¢</strong></div></div><div className="music-analytics-list">{STREAMING_PLATFORMS.map((platform: any) => { const share = Math.round((state.platformMix?.[platform.id] || 0) * 100); return <div key={platform.id}><span>{platform.name}</span><div><i style={{ width: `${share}%` }} /></div><b>{share}%</b></div>; })}</div><details className="music-nested-detail"><summary>Geographic distribution</summary><div className="music-detail-metrics">{Object.entries(state.geoDist || {}).map(([country, share]: [string, any]) => <span key={country}>{country}: {Math.round(share * 100)}%</span>)}</div></details></div></details>
    </div>}
  </div>;
}
